### ISSUE TITLE
Can I compile to bytecode on one machine and execute the vm on another?

### ISSUE THREAD

**Issue by RallyTronics** [never-lang/never#20]
I would like to play around with never on a micro-controller so would like to compile to bytecode on the PC and then execute the VM on the embedded target.  Is this feasible?

**Comment by smaludzi** [comment]
Dear RallyTronics,

I wonder how you are doing with your attempts to compile Never on the target? Maybe I could help you?

**Comment by RallyTronics** [comment]
I was never able to get the bison/flexx stuff to work on my Windows machine ( not a linux guy ) so it kind of stopped me in my tracks.  I hope to revisit it soon though.
