### ISSUE TITLE
Added Never to Rosetta Code

### ISSUE THREAD

**Issue by btiffin** [never-lang/never#21]
Hello Slawomir,

Just added Never to Rosetta Code, https://rosettacode.org/wiki/Category:Never

Being totally new to Never, I may not have all the details technically correct, so would appreciate your opinions and preferences on how to expand of the language page summary.

And, is there a way to not display the result of main, other than redirecting stderr to the null device?  A lot of the basic Rosetta tasks are console IO based, and running with 2>/dev/null for captures seems less than optimal in terms of introductory demonstrations.  *Especially for things like Hello, world*.

Have good, make well,
Brian

**Comment by smaludzi** [comment]
Being mentioned on Rosetta code is a huge news in Never community ;) actually removing return value from main was on my todo list so I will change it to process exit code shortly.

**Comment by smaludzi** [comment]
Dear Brian,

Dear Brian,

Please check sample_hello.nev for Hello World! example.

Thank you for your interest!

/Sławomir Maludziński
