### ISSUE TITLE
question about FFI

### ISSUE THREAD

**Issue by wboeke** [never-lang/never#22]
Hello,
The FFI works great in the Never language, at least for int's, float's and const strings. However...

I have the following C-code:

char *get(char *s) { return s; }
char *conc(char *s1,char *s2) {
  static char buf[20];
  sprintf(buf,"%s%s",s1,s2);
  return buf;
}

I try it in Never as follows:

extern "./issue.so" func get(s:string) -> string
extern "./issue.so" func conc(s1: string, s2:string) -> string
func main() -> int {
    prints(get("come on\n"));
    prints(conc("come ","on\n"));    /* <-- crash */
    0
}

It appears that the first statement is okay, but the second ends in a crash. Is there anything that can be done to make this work?

Best regards,
Wouter Boeke

**Comment by smaludzi** [comment]
I will check it and let you know.

**Comment by smaludzi** [comment]
Dear Wouter Boeke,

Would you check FFI calls once again? I committed a small fix.

Btw. what are you trying to use Never for?

/SM
