### ISSUE TITLE
Any plans for GC?

### ISSUE THREAD

**Issue by FrankC01** [never-lang/never#23]
Do you plan on implementing garbage collection? I've seen other issues in your log where individuals consider Never to not be a functional language because of mutability. That would eliminate Clojure as function given it's mutable underpinnings.

However; scalar or data types (lists, maps, sets, etc.) could all be immutable but the issue is it tends to generate a significant ancestry especially with heavy iteration, reductions, etc.

**Comment by smaludzi** [comment]
Thanks for interest! GC is already implemented. I am not botanist so maybe my language clasiffication be wrong, but I think the language is closest to functional languages. Everything is an expression, functions are first class. I think some purists would like to have language no side effects, but it is difficult to write programs this way. Maybe in a distant future  I will add code which will check if function is pure and make optimizations based on this but not right now. All the best!

**Comment by smaludzi** [comment]
If you have any other comments feel free to ask.

**Comment by FrankC01** [comment]
No side effects means no IO if you really want to get pure, not practical for anything else but research.
