### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by singpolyma** [never-lang/never#25]
1. `let` vs `var` are these the same except for one being mutable?
2. Type inference -- it looks like value bindings (let/var) can be inferred, but function signatures (even for small lambdas) have to be explicitly written.  Is that correct?
3. If I `nev_compile_*` two different things with the same `program`, what happens?  Does the second just overwrite the first?
4. Is there any facility to import one nev file from another, or is the idea that you're always embedding roughly self-contained scripts?

**Comment by smaludzi** [comment]
Thanks for interest.
1. Right now var and let are the same and can be modified.
2. When assigning type of variable is equal to type of expression on right hand side. I would love to infer types in other places but more work is required.
3.program is output and the function wasnt designed to be used this way.So I think you would get memory leaks.
4. Right now there are no modules. Scripts should be self contained. Right now I am working on more advanced FFI. When it is finished I have plans to work on either moduled or polymorhism. Let me know if you would like to have modules implemented.

**Comment by bogen85** [comment]
Definitely modules....

**Comment by smaludzi** [comment]
Modules are in progress. Could not test it thoroughl yet but chances are they will be in a few weeks. You may check modules branch.

**Comment by smaludzi** [comment]
Modules were delivered recently (Aug 2020).
