### ISSUE TITLE
question: Why it has `->` before return type?

### ISSUE THREAD

**Issue by delata** [never-lang/never#26]
what's the reason?
I think it is completely unnecessary.

**Comment by smaludzi** [comment]
I think that's a part of a very long discussion. Many programming languages use ':' to denote types and arrows '->' to denote function return type (see Swift, Rust or even newest releases of C++). But some only ':' to denote both type of a parameter and function (Pascal family).

**Comment by delata** [comment]
Go doesn't use any of them.
It removes clutter. make it easier to read and write. And readability is one of the most important thing of a language's syntax.

**Comment by smaludzi** [comment]
I agree. But arrows also help in reading. I am considering type inference which would make the language less verbose but it is lots of work. Anyways thanks for interest!

**Comment by smaludzi** [comment]
Closed
