### ISSUE TITLE
Using never-lang as script in Godot 

### ISSUE THREAD

**Issue by extremety1989** [never-lang/never#28]
when are you going to implement it ?

**Comment by smaludzi** [comment]
I think I will try to prepare a prototype in June/July. Of course there are questions about speed or maintability so these factors I am not taking into account yet. Likely some other functionality will be needed. We will see.

**Comment by smaludzi** [comment]
Hi extremety1989,

Sorry for delay but I was involved in implementing modules. They may also be needed in Godot framework. I also realised that I need more recent distribution of Linux to compile Godot. So there are some delays to try Godot and never-lang.

S.M.
