### ISSUE TITLE
Nice language, VM could be sped up significantly most likely

### ISSUE THREAD

**Issue by bogen85** [never-lang/never#30]
Very nice language, and from I can tell from just a short time of playing around with it, it is very fast.
Good work!

However, the never-lang VM looks looks to be using indirect call threading.

https://github.com/never-lang/never/blob/master/back/vmexec.c#L3185

Unless I'm wrong (only studied the code less than an hour) the VM could be sped up significantly, but it would take some rework.

https://eli.thegreenplace.net/2012/07/12/computed-goto-for-efficient-dispatch-tables
https://en.wikipedia.org/wiki/Threaded_code#Indirect_threading
https://www.complang.tuwien.ac.at/forth/threaded-code.html  <-- See bottom of that page for the method never-lang appears to be using.

Many other interpreted languages have gone through this as they matured....
If I find some time, I'll look at cloning never-lang/never, reworking the VM, doing a set of benchmarks on the existing vs a reworked implementation, and would do a PR. No promises though. I'd also hold off on starting any of that until after a discussion here.

Once again, good work! This is merely an observation of something that could be improved with never-lang.

**Comment by bogen85** [comment]
See http://www.complang.tuwien.ac.at/forth/threading/ for benchmarks of the various dispatch techniques.

**Comment by bogen85** [comment]
https://stackoverflow.com/questions/58774170/how-to-speed-up-dynamic-dispatch-by-20-using-computed-gotos-in-standard-c

**Comment by bogen85** [comment]
Any major rework for this would result in the majority of https://github.com/never-lang/never/blob/master/back/vmexec.c being put into one large function.

**Comment by bogen85** [comment]
Looks like the main purpose of https://github.com/never-lang/never/blob/master/back/bytecode.c is to provide a disassembly listing? That would not need to change if vmexec.c is reworked. (No need to optimize disassembly output).

https://github.com/never-lang/never/blob/master/back/bytecode.h enumerated type for opcodes would not change. However, the function prototypes in bytecode.h would no away, as those functions would be converted from functions to goto labels. From a quick spot check of a some of the execution primitives, I don't see those functions being referenced outside the VM, so this would likely not break anything.

**Comment by bogen85** [comment]
So, back to https://github.com/never-lang/never/blob/master/back/vmexec.c ...
vm_execute_op is not referenced outside of the VM, which is a good thing.
vm_execute_op_test would be be reworked to keep the index to label verification. Offhand this might take some thought, as vm_execute might not and extra argument to force this check, and that may be desirable. (Because the rework of vm_execute would cause the table to go from global to local. (Most likely).

**Comment by bogen85** [comment]
Looks like portions of https://github.com/never-lang/never/blob/master/back/vmffi.c reside inside the VM...
If I'm right about this, and If the VM is to be reworked to all reside in one function, that _might_ require those functions to moved into vm_execute as labels.
Just more to consider...

**Comment by bogen85** [comment]
Looks like only vm_execute_func_ffi in reality, and the **_magic_** it does with the other VM primitives.

**Comment by bogen85** [comment]
So, the ran the benchmarks from http://www.complang.tuwien.ac.at/forth/threading/ on modern hardware. The ratios from the original article between the various techniques still apply. 
```shell
wget http://www.complang.tuwien.ac.at/forth/threading/threading.tar.gz
gzip -cd threading.tar.gz|tar xf -
cd threading
make
```
On my machine repl-switch and direct are about the same, both are twice as fast as call threading, but the numbers are so low due to my machine being so much faster than the original numbers staged in the article.

**Comment by bogen85** [comment]
Alright, I increased the test count 100x to bring the numbers out of the noise.
Times are in seconds...
```
subroutine 2.87
direct 15.88
indirect 56.37
switch 25.82
call 34.62
repl-switch 15.07
```

repl-switch does not used computed gotos.
direct uses computed gotos.

If never-lang's vm_execute is reworked, switching between repl-switch and direct would not be hard, in order to test.

**Comment by bogen85** [comment]
Looking at how direct threading from the forth threading works, and trying to match never-lang's existing VM implementation to one of the faster methods, look's like repl-switch would be the easiest to implement.

**Comment by bogen85** [comment]
Alright, there are some primitives in https://github.com/never-lang/never/blob/master/back/vmexec.c that call other primitives directly.. That would needed to be accounted for...

**Comment by bogen85** [comment]
Well, I grabbed https://github.com/codyebberson/vm and hacked it some to do some timing comparisons on a VM where the instructions actually do something. (Made different flavors of the VM)

If I get around to it in a few days I'll make my own repo and show my timing tests.

From the Forth article mentioned earlier, repl-switch is a replicated switch, so the entire jump table is appended to the end of each instruction using a macro. For a small VM of only a few instructions that is fine, but for a larger VM that is a bit excessive in my opinion, but could be still be used if the extra speed is desirable.

I'm not done with my analysis, but will note that direct threading complicates things. The "opcodes" are no longer and index, they are a label address, so different compiles and runs of the program will result in a changing set of opcodes, so without some opcode to index conversion on save and the reverse on load, a portable VM where the bytecode could be saved and reloaded would not be achievable.

Because of this, having to rework the code emitter (initially for the codyebberson/vm, bleh, there is no code emitter, the instructions were hardcoded into an array) and potentially for never-lang (but not being able to have a portable VM I don't see as desirable). The replicated jump table for every VM instruction using repl-switch is likely less overhead (just a macro and some duplicate code) versus the complications of having to call the VM with a parameter to tell it not to run, but just to return the opcode address table, then use that table to emit code, then coming up with a way to convert the addresses back to opcode indices on saving, etc. (This is if never-lang will ever support code saving and loading). But I don't see a reworked code emitter that emits label addresses rather than opcode indices as desirable.

Switch threading (which codyebberson/vm uses) does have some speed up over call threading (which never-lang uses). However, each never-lang VM instruction is significantly more complex than each codyebberson/vm instruction, so any speed gain might not be that noticeable due to the added overhead.

So, because of the complication of direct threading, I'm not going to pursue that.

I current have for the hacked codyebberson/vm:

1. switch threading (what it came with)
2. call threading (I added this)
3. indirect threading (I added this, as the initial prep work is the same as for direct threading)

I'll add repl-switch for the comparison purposes.

It all might be a wash anyways. I started out by copying vm.c to 2 additional source files, renaming the execute function on each, then running the tests. Same code, yet the timing was different just because it got moved. Noticabley different... And different optimization settings made one flavor faster that use to be slower. So... Bleh....

This kind of stuff was so much easier when processors did not have all the branch prediction, pipelines, caches, and other other optimizations....

So, if extra speed is needed, my initial analysis shows moving to switch or repl-switch will likely show a speed improvement, but we would need to discuss this more before I pursue it.

**Comment by bogen85** [comment]
I was overthinking the complexity of dealing with direct threaded.
More on that when I complete my analysis.

**Comment by bogen85** [comment]
Direct threading was easier than I thought and dealing with portability for saved byte-code should not be an issue.

I'll provide my benchmark code based on codyebberson/vm work by the end of the weekend, but here are the timing results so far:

```
loopN = 16777215

Repl switch threaded
Expecting 920: 920
Got expected tally of 16777309: yes   duration: 1508 ms
Got expected tally of 16777309: yes   duration: 1505 ms
Got expected tally of 16777309: yes   duration: 1504 ms
Got expected tally of 16777309: yes   duration: 1512 ms
Got expected tally of 16777309: yes   duration: 1509 ms

Switch threaded
Expecting 1030: 1030
Got expected tally of 16777320: yes   duration: 1018 ms
Got expected tally of 16777320: yes   duration: 1018 ms
Got expected tally of 16777320: yes   duration: 1018 ms
Got expected tally of 16777320: yes   duration: 1018 ms
Got expected tally of 16777320: yes   duration: 1019 ms

Call threaded
Expecting 1140: 1140
Got expected tally of 16777331: yes   duration: 2093 ms
Got expected tally of 16777331: yes   duration: 2092 ms
Got expected tally of 16777331: yes   duration: 2092 ms
Got expected tally of 16777331: yes   duration: 2091 ms
Got expected tally of 16777331: yes   duration: 2093 ms

Indirect threaded
Expecting 1250: 1250
Got expected tally of 16777342: yes   duration: 368 ms
Got expected tally of 16777342: yes   duration: 368 ms
Got expected tally of 16777342: yes   duration: 369 ms
Got expected tally of 16777342: yes   duration: 368 ms
Got expected tally of 16777342: yes   duration: 368 ms

Direct threaded  sizeof(long)==8
Expecting 1690: 1690
Got expected tally of 16777383: yes   duration: 352 ms
Got expected tally of 16777383: yes   duration: 352 ms
Got expected tally of 16777383: yes   duration: 352 ms
Got expected tally of 16777383: yes   duration: 353 ms
Got expected tally of 16777383: yes   duration: 352 ms
```

Repl switch threaded results from earlier tests were skewed, because the instructions were noops.

Here is Ocaml's threading, very similar to what I'm thinking about for never-lang: https://github.com/ocaml/ocaml/blob/trunk/runtime/interp.c

Based on this I'm leaning towards direct threading now for what I'd like to contribute for never-lang for VM speedup.

I'd convert it in the following stages:
1. From call to switch
2. From switch to indirect
3. From indirect to direct

The work for each builds on the previous, but that is from the simplest to the most complex.

**Comment by bogen85** [comment]
Alright, here is code that demonstrates the various threading techniques.
https://github.com/bogen85/vm

**Comment by bogen85** [comment]
So, I'd like to pursue refactoring never-lang's VM from call threaded to direct threaded (with the ability to save/load reusable byte-code) without changing how the code is compiled (apart from some needed changes to the emitter) and what each instruction does (as far as what it is supposed to accomplish). But I want to discuss a few things first on that.

**Comment by smaludzi** [comment]
Having demonstrated speed up is very tempting. On the other hand I am afraid of turning vm code into huge function. Maybe using macros or some other ways can keep code clean. Lets first measure actual speed up which can be achieved as those numbers, if I understand correctly, are only for simple programs. Btw. some time ago I found scripting languages vm speed comparision but now I can't. Would be interesting to see where these optimization will take us. Btw2. I used mimalloc library which also improved vm speed.

**Comment by bogen85** [comment]
Yeah, this is why I wanted to hold off on pursuing this until after discussing it with you.

Agreed on how much it could speed up Never, as a opposed to a VM where the primitives are a lot simpler (As in a language like Forth). And while I was rambling a bit (because in the past I had not actually ever implemented direct or indirect threading, only switch and call threading, and did not know how hard it would be to refactor switch to call, or switch to direct, and what would be involved), I did bring that earlier in the discussion:
```
Switch threading (which codyebberson/vm uses) does have
some speed up over call threading (which never-lang uses).
However, each never-lang VM instruction is significantly
more complex than each codyebberson/vm instruction,
so any speed gain might not be that noticeable due to the
added overhead.
```

As far as single function, as long as they are in the same file and marked as inline the same effect of macros may be achieved. But then all the VM instructions would need to reside in one file. (Or use ```#include``` if they reside in other files, rather than being linked). Marking them inline and using include would significantly reduce refactoring overhead. However, with current dispatch in vmexec no in-lining would take place, because the function address is retrieved from a table and called:
```
    while (machine->running == VM_RUNNING)
    {
        bc = prog->module_value->code_arr + machine->ip;
        machine->ip++;
        vm_execute_op[bc->type].execute(machine, bc);

        if (machine->running == VM_EXCEPTION)
        {
            machine->ip = exception_tab_search(prog->module_value->exctab_value,
                                               machine->ip - 1);
            machine->running = VM_RUNNING;
        }
    }
```
As far as the discussion of setjmp/longjmp to jump out of the VM, if the VM is all in one function, goto could be used. However, that would not allow for in-lining, all would have to reside in the same function. Guard pages (discussed in #36 would require setjmp/longjmp to recover from.)

And as far as delaying refactoring the current high level VM (because of the instruction overhead vs dispatch overhead), an all in one function VM would make more sense for the never lang subset I was discussing in #34 (That would reside in a module and other code, and would not need to reside in the core never-lang code base).

**Comment by bogen85** [comment]
Yeah, Lua and LuaJit would be interesting, you would be using their GC, a lot of effort (and a lot peer review) have been put into optimizing the Lua runtime.

**Comment by bogen85** [comment]
The Lua runtime is for a dynamically language, vs something like ocaml which is a statically typed language.
So the Lua runtime is likely not going to optimize for static typing.

I don't see a side by side comparison on these:
- https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/lua.html
- https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/ocaml.html

However, those numbers are for non LuaJit Lua and natively compiled ocaml, so comparing use those results would not be fair.

Ocaml does have a portable bytecode format. I see at least one example someone targeting that, but that is from an ocaml front end... (would like to find one in C..)
- https://github.com/nojb/ocaml-c0

I might research the ocaml bytecode format and see what it would take to target that. However, I could not find if there is a way to feed ocaml bytecode into the ocaml native compiler, if there is not, then longterm it would not likely be a good format to target. I'd likely want to see if that could be done first (converting ocaml bytecode to ocaml native) before going down that rabbit hole.

I'd like to see some LuaJit vs ocaml native comparisons.

**Comment by bogen85** [comment]
There are these:
- https://ocaml.org/meetings/ocaml/2012/abstracts/oud2012-final10.pdf
- https://github.com/bvaugon/ocamlcc

So that would allow ocaml bytecode to be converted to C and ran through an optimizing compiler.

But the overhead of having ocaml installed to run never code might be a bit extreme. Pursing Lua and LuaJit maybe a lot more practical, even if not as optimized.

**Comment by bogen85** [comment]
I looked into Lua/LuaJIT some. Certainly looks to be simpler or practical option than going, say, the ocaml intermediate route.

Were you thinking of targeting Luajit compatible bytecode or transpiling via lua using luajit libraries?

**Comment by bogen85** [comment]
This is interesting https://eliasdaler.github.io/luavela/

**Comment by bogen85** [comment]
Ravi might be interesting to consider as well, Lua 5.3+, 64 bit for integers and float
- https://github.com/dibyendumajumdar/ravi
- https://the-ravi-programming-language.readthedocs.io/en/latest/ravi-reference.html

Plus a few different JIT back-ends including LLVM.

**Comment by smaludzi** [comment]
I think we misunderstood each other. By targeting I meant achieving similar VM execution speed as Lua not compiling never to Lua bytecode. The other thing whatsoever is that maybe in a distant furture it would be nice to have JIT in never as well.

**Comment by bogen85** [comment]
@smaludzi thank you for the clarification. Based on my musing in #34 when you mentioned "targeting Lua" I was a little concerned, because based on what I'd saw of never-lang prior your goals seemed in line with what I want to achieve. When you said "targeting Lua" I was starting to wonder about my earlier assumptions. 

Now I see they still do, so thanks!

**Comment by bogen85** [comment]
Well, inline functions won't give us the speed up of direct threaded. However, it is not moving the VM primitive code bodies into inline functions that causes the performance hit, it is the usage of a shared VM variable frame. Before I moved the code out of the VM function, I converted the VM primitives to use a pointer to the VM variable frame. The timing results after making that change did not change after I moved the code into the inline functions. So, inline functions are just as good as C preprocessor macros with the exception that they can't share local variables.

So to get the benefits of direct threaded one must either put the VM primitives inside the VM function, or define them all as macros so they can reside outside the VM function.

- https://github.com/bogen85/threaded-code-techniques
- See direct threaded inline call
```
loopN = 16777215

Repl switch threaded
Expecting 970: 970
Got expected tally of 16777314: yes   duration: 1478 ms
Got expected tally of 16777314: yes   duration: 1474 ms
Got expected tally of 16777314: yes   duration: 1477 ms
Got expected tally of 16777314: yes   duration: 1475 ms
Got expected tally of 16777314: yes   duration: 1477 ms

Switch threaded
Expecting 1080: 1080
Got expected tally of 16777325: yes   duration: 1037 ms
Got expected tally of 16777325: yes   duration: 1036 ms
Got expected tally of 16777325: yes   duration: 1036 ms
Got expected tally of 16777325: yes   duration: 1036 ms
Got expected tally of 16777325: yes   duration: 1035 ms

Call threaded
Expecting 1190: 1190
Got expected tally of 16777336: yes   duration: 2052 ms
Got expected tally of 16777336: yes   duration: 2048 ms
Got expected tally of 16777336: yes   duration: 2051 ms
Got expected tally of 16777336: yes   duration: 2051 ms
Got expected tally of 16777336: yes   duration: 2051 ms

Indirect threaded
Expecting 1300: 1300
Got expected tally of 16777347: yes   duration: 385 ms
Got expected tally of 16777347: yes   duration: 386 ms
Got expected tally of 16777347: yes   duration: 386 ms
Got expected tally of 16777347: yes   duration: 386 ms
Got expected tally of 16777347: yes   duration: 386 ms

Direct threaded  sizeof(long)==8
Expecting 1740: 1740
Got expected tally of 16777388: yes   duration: 493 ms
Got expected tally of 16777388: yes   duration: 502 ms
Got expected tally of 16777388: yes   duration: 487 ms
Got expected tally of 16777388: yes   duration: 492 ms
Got expected tally of 16777388: yes   duration: 501 ms

Direct threaded inline call
Expecting 2230: 2230
Got expected tally of 16777436: yes   duration: 857 ms
Got expected tally of 16777436: yes   duration: 848 ms
Got expected tally of 16777436: yes   duration: 848 ms
Got expected tally of 16777436: yes   duration: 848 ms
Got expected tally of 16777436: yes   duration: 847 ms

Direct threaded using offsets
Expecting 2670: 2670
Got expected tally of 16777481: yes   duration: 386 ms
Got expected tally of 16777481: yes   duration: 386 ms
Got expected tally of 16777481: yes   duration: 386 ms
Got expected tally of 16777481: yes   duration: 386 ms
Got expected tally of 16777481: yes   duration: 387 ms
```

**_And something interesting to note... Direct threaded performance got worse with no code changes... Just moving stuff around in the what is linked changes timings..._**

**Comment by bogen85** [comment]
I'll revisit this later, closing this for now.

**Comment by smaludzi** [comment]
Hi Bogen,

Are you still interested in Never? I did a small demo to check direct/in-direct speed-up. It seems that 10-20% improvement can be achieved. This is similar to results reported by [CPython implementation](https://github.com/python/cpython/blob/master/Python/ceval.c#L1002).

You may try the following code. I tried to prepare version which uses same code for switch/direct threading version (sorry if I confuse names of those bytecode execution techniques).

#include <stdio.h>

#define MAX_STACK 200

typedef enum opcode {
    OP_INIT = 0,
    OP_PUSH,
    OP_POP,
    OP_ADD,
    OP_BEG,
    OP_PRINT,
    OP_END
} opcode;

typedef struct VM
{
    int ip;
    int sptr;
    int stack[MAX_STACK];
} VM;

typedef struct bytecode
{
    opcode op;
    int value;
} bytecode;

#define def_init(header, footer) \
    header \
    { \
        vm->ip = 0; \
        vm->sptr = -1; \
    } \
    footer \

def_init(void exec_init(bytecode * code, VM * vm), ;)

#define def_push(header, footer) \
    header \
    { \
        vm->sptr++; \
        vm->stack[vm->sptr] = code[vm->ip].value; \
    } \
    footer \

def_push(void exec_push(bytecode * code, VM * vm), ;)

#define def_pop(header, footer) \
    header \
    { \
        vm->sptr--; \
    } \
    footer

def_pop(void exec_pop(bytecode * code, VM * vm), ;)

#define def_add(header, footer) \
    header \
    { \
        int sum = 0; \
        sum = vm->stack[vm->sptr - 1] + vm->stack[vm->sptr]; \
        vm->sptr--; \
        vm->stack[vm->sptr] = sum; \
    } \
    footer

def_add(void exec_add(bytecode * code, VM * vm), ;)

#define def_beg(header, footer) \
    header \
    { \
        static int loop = 0; \
        if (loop++ < 1000000) \
        { \
            vm->ip = -1; \
        } \
    } \
    footer

def_beg(void exec_beg(bytecode * code, VM * vm), ;)

#define def_print(header, footer) \
    header \
    { \
        printf("%d\n", vm->stack[vm->sptr]); \
    } \
    footer

def_print(void exec_print(bytecode * code, VM * vm), ;)

#define def_end(header, footer) \
    header \
    { \
        printf("END\n"); \
    } \
    footer

def_end(void exec_end(bytecode * code, VM * vm), ;)

#define next \
    goto *labels[code[++vm->ip].op]; \

typedef struct opcode_exec
{
    opcode op;
    void (*exec) (bytecode * code, VM * vm);
} opcode_exec;

opcode_exec opcodes[] = 
{
    {  OP_INIT, exec_init },
    {  OP_PUSH, exec_push },
    {  OP_POP,  exec_pop },
    {  OP_ADD,  exec_add },
    {  OP_BEG, exec_beg },
    {  OP_PRINT, exec_print },
    {  OP_END, exec_end },
};

void exec(bytecode * code, VM * vm)
{
    do
    {
        vm->ip++;
        opcodes[code[vm->ip].op].exec(code, vm);
    }
    while (code[vm->ip].op != OP_END);
}

void exec_th(bytecode * code, VM * vm)
{
    int end = 0;
    static void * labels[] = { &&init, &&push, &&pop, &&add, &&beg, &&print, &&end };

    while (end == 0)
    {
        next
    
        def_init(init:, next)
        def_push(push:, next)
        def_pop(pop:, next)
        def_add(add:, next)
        def_beg(beg:, next)
        def_print(print:, next)
        def_end(end:, end = 1;)
    }
}

bytecode code[] = { { OP_INIT, 0 }, { OP_PUSH, 20 }, { OP_PUSH, 20 }, { OP_ADD, 0 }, { OP_BEG, 0 }, { OP_PRINT, 0 }, { OP_END, 0 } };
/* bytecode code[] = { { OP_INIT, 0 }, { OP_PUSH, 20 }, { OP_PUSH, 20 }, { OP_ADD, 0 }, { OP_PRINT, 0 }, { OP_END, 0 } }; */

int main(int argc, char * argv[])
{
    VM vm = { .ip = -1 };

    exec(code, &vm);

    return 0;
}

**Comment by bogen85** [comment]
I've been busy with other things, but Never has inspired me a lot.

There still seems to some levels of indirection with your next, but I'm not sure how that can be avoided, as C does not have nested functions to hold your VM state. So you took a hybrid approach, which as you have shown, does some speed up.

By inspired, I mean I often contemplated writing my own language, and Never has a lot of overlap with my desired end goal.  Most people write dynamic languages, but I prefer the compiler to validate things for me.

My main focus for what I want though is for embedded systems. My primarily goals are statically typed, small VM (or native code, I'm looking at MIR/Jit) and a REPL (can to tethered to a host system, the bulk of the code for the REPL would be on the host, only the actual execution would be on the target). Also I need the GC to be able to be disabled (which I know for the most part kills closure functionality, which kills most functional programming functionality), as I'd run multiple threads on the target, some GC'ed, some not, where the GC'ed threads would prioritized in such as way as to not affect real time. I'd also need a configurable GC, that would not exceed memory and time constraints.

I'd made a few attempts at the past, but never worked out a clean design of what the language should look like, and never is very close. As far as implementation language, I've consider several (D, C, C++, Rust, Pascal), but am settling Ada, as GNU Ada is well supported on Linux and many embedded platforms and meets more of my implementation language requirements more than C and the others do. Plus I've done a lot of Pascal in the past, so Ada is not uncomfortable for me.

A debugger with REPL like functionality is not the same as a true REPL that is baked into the language design.

Never's design seems to be focused on whole program at a time compilation, which essentially rules out a REPL, where one would be adding snippets to an existing program and running those snippets.

**Comment by smaludzi** [comment]
Nice to hear I inspired you. You also mentioned a few improvements which I already have begun to implement.

Wrt to statically typed language which supports REPL I imagine a runtime which changes AST on every command which is typed, performs checks and runs it. But this is just a quick idea.

Good luck. If you have any other comments, please feel free to drop me a comment.

BR,
SM
