### ISSUE TITLE
never 2.1.2 build failure

### ISSUE THREAD

**Issue by chenrui333** [never-lang/never#50]
👋  it looks like there is some build issue with the 2.1.2 release, the build error log is below:

```
==> cmake ..
==> make
Last 15 lines from /Users/rchen/Library/Logs/Homebrew/never/02.make:
make

/usr/local/Cellar/cmake/3.21.1/bin/cmake -S/tmp/never-20210822-10267-kpy8ma/never-2.1.2 -B/tmp/never-20210822-10267-kpy8ma/never-2.1.2/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.21.1/bin/cmake -E cmake_progress_start /tmp/never-20210822-10267-kpy8ma/never-2.1.2/build/CMakeFiles /tmp/never-20210822-10267-kpy8ma/never-2.1.2/build//CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/nev.dir/build.make CMakeFiles/nev.dir/depend
[  0%] [BISON][parser] Building parser with bison 2.3
[  1%] [FLEX][scanner] Building scanner with flex 2.5.35
cd /tmp/never-20210822-10267-kpy8ma/never-2.1.2 && /usr/bin/bison -d --verbose -o /tmp/never-20210822-10267-kpy8ma/never-2.1.2/front/parser.c /tmp/never-20210822-10267-kpy8ma/never-2.1.2/front/parser.y
cd /tmp/never-20210822-10267-kpy8ma/never-2.1.2 && /usr/bin/flex -o/tmp/never-20210822-10267-kpy8ma/never-2.1.2/front/scanner.c /tmp/never-20210822-10267-kpy8ma/never-2.1.2/front/scanner.l
/tmp/never-20210822-10267-kpy8ma/never-2.1.2/front/parser.y:210.9-16: syntax error, unexpected identifier, expecting string
make[2]: *** [../front/parser.c] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/nev.dir/all] Error 2
make: *** [all] Error 2
```

relates to Homebrew/homebrew-core#70629

**Comment by smaludzi** [comment]
Would you try mkdir build ; cmake .. ; make ? I am almost sure there is no build error.

**Comment by smaludzi** [comment]
Also try using make VERBOSE=1 so more output is available

**Comment by smaludzi** [comment]
I tried the following archive https://github.com/never-lang/never/archive/refs/tags/v2.1.2.tar.gz and never built successfully.

I am using the following gcc version:

gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Comment by kuba--** [comment]
@chenrui333 - it's because of the old version of `bison`
> Building parser with bison 2.3

That's why in `../front/parser.y:212` it could not understand `%define api.pure`
If you upgrade bison (I've upgraded with homebrew to 3.7.6), it should work fine.

**Comment by kuba--** [comment]
...so just in case I sent PR: https://github.com/never-lang/never/pull/51 which requires bison in at least v2.7.1

**Comment by smaludzi** [comment]
@chenrui333 please try release version v2.1.8. If everything works fine I will close the issue.

**Comment by chenrui333** [comment]
Sorry about the delay, checking with [the release 2.1.8 now](https://github.com/Homebrew/homebrew-core/pull/84224)
