### ISSUE TITLE
test/test_inttab.c: constant comparison

### ISSUE THREAD

**Issue by b4yuan** [never-lang/never#52]
In lines 62-66:

```
for (value = 16; value < 16; value++)
    {
        inttab_entry * entry = inttab_lookup(tab, value);
        assert(entry != NULL && entry->value == value);
    }
```

and lines 81-85:

```
for (value = 16; value < 16; value++)
    {
        inttab_entry * entry = inttab_lookup(tab, value);
        assert(entry != NULL && entry->value == value);
    }
```

`value` is always >= 16 and these statements will always evaluate to false. Comparison is redundant and suggests the possibility of a bug.

**Comment by kuba--** [comment]
I think it's a typo (in the test), It should be `-16`. Fix PR: https://github.com/never-lang/never/pull/53

**Comment by Machiry** [comment]
Hey @kuba-- ,

I am Aravind Machiry, an Assistant Professor at Purdue's ECE Department.

This pull request (along with several others) is the result of our ongoing research work (along with @szsam) to improve the security of open-source embedded projects.

We are doing a short (5-minute) survey to understand the use of static analysis tools in embedded projects.

It would greatly benefit our research if you could fill out this anonymous survey: https://purdue.ca1.qualtrics.com/jfe/form/SV_0OnXfr5plPe1QCa

Thank you,
Aravind
