### ISSUE TITLE
Command-line arguments

### ISSUE THREAD

**Issue by rzuckerm** [never-lang/never#56]
How does a program get its command-line arguments? I can't seem to find anything in the documentation. The closest thing I found is [this](https://never-lang.readthedocs.io/en/latest/#shell). However, there doesn't seem to be anything called `nev` that I can use.

**Comment by smaludzi** [comment]
I am on holidays. Will get back to you soon.

**Comment by rzuckerm** [comment]
Is it possible to treat the command-line arguments as an array of strings? Ideally, I'd like something like this:
```
func main(argv[N]: string) -> int
{
    ... do some command-line arguments parsing ...
    ... if invalid arguments , display some error message and exit ...
    ... do some processing on the command-line arguments ...
    0
}
```

**Comment by rzuckerm** [comment]
BTW, I tried something like this just to see if I could process a single string argument:
```
func main(s: string) -> int
{
    prints(s + "\n");
    0
}
```
I got this error:
```
cannot find entry main
```

**Comment by smaludzi** [comment]
I pushed a PR with a change which lets `string`s to be passed to `main`. Please check `string_passed_to_main` branch. It is a small patch. I think in a similar manner arrays can be passed but I need to spend a little bit more time (e.g. some syntax on command line to differ between params and arrays of params).

**Comment by rzuckerm** [comment]
@smaludzi Thanks for doing this, but it's not really what I need. What I need is a way to tell the `never` interpreter/compiler to treat command-line arguments as an array of strings and let the program figure out what to do from there. All other languages I've used either provide the command-line arguments and the number of arguments as parameters to the `main` function (like C, C++, and Java), a global variable (like PHP), or provide a module/function to get the command-line arguments (like Python, Rust, etc.). In other words, it would be nice if I could do something like this:
```
never -f foo.nev --args-as-str-array <args>
```
where `<args>` can be 0 or more command-line arguments.

**Comment by smaludzi** [comment]
I understand. That's good idea and I will try to implement such functionality but it will take a while. You may also try, I think places in the mentioned PR are good starting point.

**Comment by rzuckerm** [comment]
@smaludzi No problem, I can wait.

**Comment by smaludzi** [comment]
Hi, Please check the latest commit on `string_passed_to_main`. I think it is what you requested for.

P.S. It came to my mind that I can also support arrays of integers and floats, but I will add this later.

**Comment by rzuckerm** [comment]
@smaludzi While I can't claim that understand all the code in the PR, it looks like what I want. Thanks! Looking forward to this being merged so that I can use it.

**Comment by smaludzi** [comment]
@rzuckerm I delivered the pull request. Best regards.

**Comment by rzuckerm** [comment]
Thanks, @smaludzi . However, I'm seeing one problem. If I don't pass any arguments, I'm getting this error message:
```
too few parameters, expected 1 got 0
```
I'm working around this by passing a dummy argument (`--args`) that the program will ignore.

**Comment by smaludzi** [comment]
Yes, I am aware of this limitation. I am working to change this as right now arrays cannot be empty. I will let you know once patch is ready.

**Comment by smaludzi** [comment]
Hi, It seems now it is possible to use empty arrays. I am closing the issue.
