### ISSUE TITLE
Question: Official release

### ISSUE THREAD

**Issue by rzuckerm** [never-lang/never#60]
When is the next official release of the Never language? For my programming language docker images, I prefer to use a release tag. Currently, I'm just using the latest commit hash.

**Comment by smaludzi** [comment]
Hmm. There is no release plan defined. I will create a new tag based on the latest & greatest as the code seems stable.

Btw. What are you creating Docker images for?

**Comment by smaludzi** [comment]
Hi. I created a new release. https://github.com/never-lang/never/releases/tag/v2.3.9

**Comment by rzuckerm** [comment]
@smaludzi The docker images are for a project called [Sample Programs in Every Language](https://github.com/TheRenegadeCoder/sample-programs). When I cannot find an existing docker image for a particular programming language, I create one myself.

**Comment by smaludzi** [comment]
Thank you. I treat it as distinction. If you have any issues feel free to
submit them. I will try to help you.

BR,
SM


sob., 2 wrz 2023, 22:19 użytkownik rzuckerm ***@***.***>
napisał:
